---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-api-deployment
spec:
  selector:
    matchLabels:
      app: cms-api # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: cms-api # 标签
    spec:
      containers:
      - name: cms-api
        image: {{ .Values.cms_api.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.cms_api.port }}
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"     
      volumes:
        - name: config
          configMap:
            name: openim-config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新
---
apiVersion: v1
kind: Service
metadata:
  name: cms-api
spec:
  ports:
    - name: cms-api-port
      protocol: TCP
      port: {{ .Values.cms_api.port }}
      targetPort: {{ .Values.cms_api.port }}
  selector:
    app: cms-api
  type: NodePort  