---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-gateway-deployment
spec:
  selector:
    matchLabels:
      app: msg-gateway # 选择这个指定标签执行
  replicas: 1 # 运行pod数量
  template:
    metadata:
      labels:
        app: msg-gateway # 标签
    spec:
      containers:
      - name: msg-gateway
        image: {{ .Values.msg_gateway.image }}
        # imagePullPolicy: Always
        ports:
        - name: rpc-port
          containerPort: {{ .Values.msg_gateway.rpcport }}
        - name: ws-port
          containerPort: {{ .Values.msg_gateway.wsport }}
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
        env:
          - name: CONFIG_NAME
            value: "/Open-IM-Server"         
      volumes:
        - name: config
          configMap:
            name: openim-config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新
---
apiVersion: v1
kind: Service
metadata:
  name: msg-gateway
spec:
  ports:
    - name: msg-gateway-port
      protocol: TCP
      port: {{ .Values.msg_gateway.wsport }}
      targetPort: ws-port
  selector:
    app: msg-gateway
  type: NodePort   

    